config/routes.rb
Trovu::Application.routes.draw do

  get '/admin', to: 'admin#index', as: '/' 
  resources :empresas do 
    resources :sucursals do
      resources :menu_entries
    end
    resources :trovu_suscriptions 
    resources :payments
    post "/count_a_view" => 'empresas#count_a_view'
    get "/debts" => 'empresas#debts'
  end

  resources :payment_types

  get "admin/index"
  get "/" => "trovu#index"
  get "/almuerzo_cena" => "trovu#alCen" 
  get "/desayuno_merienda" => "trovu#desMer"
  get "/mas_cercanos" => "trovu#masCercanos"
  get "/top10" => "trovu#top10"
  get "/destacados" => "trovu#destacados"
  get "/nuevos" => "trovu#nuevos"
  get "/conocenos" => "trovu#conocenos"
  get "/legal" => "trovu#legal"
  get "/contactanos" => "trovu#contactanos"
  get "/faq" => "trovu#faq"
  get "/locales" => "trovu#locales"
  match '/search', to: 'trovu#search', via: "get"
  root "trovu#index"
end

app/models/categorization.rb
class Categorization < ActiveRecord::Base
  belongs_to :sucursal
  belongs_to :sub_category
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :sub_categories
end

app/models/empresa.rb
class Empresa < ActiveRecord::Base
	has_many :sucursals
	has_many :publicidads
	has_many :trovu_suscriptions
	validates_uniqueness_of :nombre 
  	has_attached_file :logotipo, :styles => { :medium => "300x300>", :mini => "30x30>" },
	:url  => "/assets/pictures/:id/:style/:basename.:extension",
    :path => ":rails_root/public/assets/pictures/:id/:style/:basename.:extension",
    :default_url => '/assets/defaults/rest/restaurant-default_:style.png'
    validates_attachment_size :logotipo, :less_than => 1.megabytes
  	validates_attachment_content_type :logotipo, :content_type => /\Aimage\/.*\Z/

    after_create :check_suscribed
    after_update :check_pays

    private
    def check_pays
      if (self.pays_changed? && self.pays == true)
        add_suscription
      end
    end

    private
    def check_suscribed
      if (self.pays)
        add_suscription
      end
    end

    private
    def add_suscription
        
        expireDate = Date.today + 1.year
        suscription = TrovuSuscription.create(empresa: self, expires_on: expireDate);
    end

  	public
  	def expiration_date
  		expDate = nil

  		if self.pays
  			expDate = trovu_suscriptions.last.expires_on
  		else
  			expDate = Date.today - 1.day
  		end
  		return expDate
  	end

  	public 
  	def on_date
  		return self.expiration_date >= Date.today
  	end

    public
    def count_a_view
      lastCount = self.visit_count
      if (lastCount == nil)
        lastCount = 0
      end
      self.visit_count = lastCount + 1
      self.save
    end
    public
    def get_logo
      logo = nil
      if self.pays
        logo = self.logotipo
      end
      return logo
    end

    public
    def debt_payments

      payments = []
      TrovuSuscription.includes(:payment).joins(:payment).where(empresa: self, payments: {payed: false}).find_each do |aSuscription|
        payments<<aSuscription.payment
      end

      payments
    end

    public
    def has_any_debt
      return debt_payments.size > 0
    end
end

app/models/menu_entry.rb
class MenuEntry < ActiveRecord::Base
  belongs_to :sucursal
  validates_presence_of :sucursal
end

app/models/payment.rb
class Payment < ActiveRecord::Base
	belongs_to :payable, polymorphic: true
	belongs_to :payment_type
	after_update :verify_payed

	private
	def type
		self.payment_type
	end

	private
	def verify_payed
		print "here!!\n\n\n---\n\n\n"
		if self.payed_changed? && self.payed == true
			self.update_column(:payment_date, Date.today)
		end
	end
end

app/models/payment_type.rb
class PaymentType < ActiveRecord::Base
	has_many :payments

end

app/models/publicity.rb
class Publicity < ActiveRecord::Base
  belongs_to :empresa
  has_one :payment, as: :payable
end

app/models/sub_category.rb
class SubCategory < ActiveRecord::Base
  belongs_to :category
  has_many :categorizations;
  has_many :sucursals, :through => :categorizations
end

app/models/sucursal.rb
class Sucursal < ActiveRecord::Base
	belongs_to :empresa
	has_many :menu_entries
	has_many :telefonos
	has_many :turnos
	has_many :categorizations
	has_many :sub_categories, :through => :categorizations
end

app/models/telefono.rb
class Telefono < ActiveRecord::Base
	belongs_to :sucursal
end

app/models/trovu_suscription.rb
class TrovuSuscription < ActiveRecord::Base
  belongs_to :empresa
  has_one :payment, as: :payable
  after_create :add_pendent_pay

  private 
  def add_pendent_pay
  	Payment.create(payable: self)
  end
end

app/models/turno.rb
class Turno < ActiveRecord::Base
	belongs_to :sucursal
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
 # http_basic_authenticate_with name: "trovuAdmin", password: "trovu"
  def index
  	@empresas = Empresa.all
  end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/empresas_helper.rb
module EmpresasHelper
end

app/helpers/menu_entries_helper.rb
module MenuEntriesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/sucursals_helper.rb
module SucursalsHelper
end

app/helpers/trovu_helper.rb
module TrovuHelper
end

app/views/admin/_footer.html.erb
<div id = "footer" class = "gradient">

</div> 

app/views/admin/_header.html.erb
<div id = "header" class = "gradient">
	
	<div id = "headerCont">
		<%= link_to (image_tag "logo-border280x125.png", id: "logoImg"), controller: "admin", action: "index"%>
		<h1 id = 'headerTitle'>
			<%=link_to "Portal Administrativo", controller: "admin", action: "index"%>
		</h1>
	</div>

</div>

<div class = "clear"></div>

app/views/admin/_show_empresa_sucursals.html.erb
<script type="text/javascript"
      src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDLE-I4mF-_-5om09EbV5NvcZwDozeAJIg&sensor=false">
</script>

<script type="text/javascript">
	var mapOptions = {
		center: new google.maps.LatLng(<%=lat%>, <%=lng%>),
		zoom: 16,
		maxZoom:16,
		minZoom:16,
		mapTypeControl: false,
		streetViewControl: false, 
		draggable: false,
		zoomControl: false
	};
	var map = new google.maps.Map(document.getElementById("map-canvas"), mapOptions);

	var i = 0;
	<% empresa.sucursals.each do |s| %>
		i++;
		new google.maps.Marker({
			position: new google.maps.LatLng(<%=s.latitud%>, <%=s.longitud%>),
			map: map,
			title: "Sucursal "+i,
			icon: "/assets/favicon.png"
		});
	<% end %>

	
</script>

app/views/admin/index.html.erb
<h2>Gestor de empresas afiliadas</h2>

<% i = 0 %>

<table id = "enterpriseList">

	<% if @empresas.any? %>

		<tr>
		<%@empresas.each do |e|%>

			<td class = "aEnterprise">
			<div class = "adm-empresa">
				<h3><%=e.nombre%></h3>
				<%=image_tag e.logotipo.url(:mini)%><br>
				<%=link_to 'Ver', empresa_path(e)%>
				<%=link_to 'Editar', edit_empresa_path(e)%>
				<%=button_to 'Delete', empresa_path(e), method: :delete, data: {confirm: "esta seguro?"}%>

			</div>
			</td>
			<% i += 1 %>
			<% if ((i % 5) == 0) %>
				</tr><tr>
			<% end %>

		<%end%>
		</tr>

	<% else %>
		<i>Aun no hay empresas afiliadas</i>
	<% end %>
</table>


<br><br>
<%=link_to "Afiliar Nueva Empresa", new_empresa_path%> <br> <br>
<div class = "small-font">
<%=link_to "Editar tipos de pago (confirmar esto)", payment_types_path%>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Trovu</title>
  
  <%= favicon_link_tag 'favicon.ico' %>
  <%= stylesheet_link_tag "admin/admin"%>
  <%= javascript_include_tag "admin/admin"%>
  <%= csrf_meta_tags %>
</head>
<body>

<%=render 'admin/header'%>

<div id = "page">
	<%= yield %>
</div>
<%=render 'admin/footer'%>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Trovu</title>
  
  <%= favicon_link_tag 'favicon.ico' %>
  <%= stylesheet_link_tag "application"%>
  <%= javascript_include_tag "application"%>
  <link href='http://fonts.googleapis.com/css?family=Lato:300,400,700' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
</head>
<body>

<%=render 'header'%>

<div id = "page">
	<%= yield %>
</div>
<%=render 'footer'%>

</body>
</html>