config/routes.rb
Trovu::Application.routes.draw do

  get '/admin', to: 'admin#index', as: '/' 
  resources :empresas do 
    resources :sucursals do
      resources :menu_entries
    end
    resources :trovu_suscriptions 
    resources :payments
    post "/count_a_view" => 'empresas#count_a_view'
    get "/debts" => 'empresas#debts'
  end

  resources :payment_types

  get "admin/index"
  get "/" => "trovu#index"
  get "/almuerzo_cena" => "trovu#alCen" 
  get "/desayuno_merienda" => "trovu#desMer"
  get "/mas_cercanos" => "trovu#masCercanos"
  get "/top10" => "trovu#top10"
  get "/destacados" => "trovu#destacados"
  get "/nuevos" => "trovu#nuevos"
  get "/conocenos" => "trovu#conocenos"
  get "/legal" => "trovu#legal"
  get "/contactanos" => "trovu#contactanos"
  get "/faq" => "trovu#faq"
  get "/locales" => "trovu#locales"
  match '/search', to: 'trovu#search', via: "get"
  root "trovu#index"
end

app/models/categorization.rb
class Categorization < ActiveRecord::Base
  belongs_to :sucursal
  belongs_to :sub_category
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :sub_categories
end

app/models/empresa.rb
class Empresa < ActiveRecord::Base
	has_many :sucursals
	has_many :publicidads
	has_many :trovu_suscriptions
	validates_uniqueness_of :nombre 
  	has_attached_file :logotipo, :styles => { :medium => "300x300>", :mini => "30x30>" },
	:url  => "/assets/pictures/:id/:style/:basename.:extension",
    :path => ":rails_root/public/assets/pictures/:id/:style/:basename.:extension",
    :default_url => '/assets/defaults/rest/restaurant-default_:style.png'
    validates_attachment_size :logotipo, :less_than => 1.megabytes
  	validates_attachment_content_type :logotipo, :content_type => /\Aimage\/.*\Z/

    after_create :check_suscribed
    after_update :check_pays

    private
    def check_pays
      if (self.pays_changed? && self.pays == true)
        add_suscription
      end
    end

    private
    def check_suscribed
      if (self.pays)
        add_suscription
      end
    end

    private
    def add_suscription
        
        expireDate = Date.today + 1.year
        suscription = TrovuSuscription.create(empresa: self, expires_on: expireDate);
    end

  	public
  	def expiration_date
  		expDate = nil

  		if self.pays
  			expDate = trovu_suscriptions.last.expires_on
  		else
  			expDate = Date.today - 1.day
  		end
  		return expDate
  	end

  	public 
  	def on_date
  		return self.expiration_date >= Date.today
  	end

    public
    def count_a_view
      lastCount = self.visit_count
      if (lastCount == nil)
        lastCount = 0
      end
      self.visit_count = lastCount + 1
      self.save
    end
    public
    def get_logo
      logo = nil
      if self.pays
        logo = self.logotipo
      end
      return logo
    end

    public
    def debt_payments

      payments = []
      TrovuSuscription.includes(:payment).joins(:payment).where(empresa: self, payments: {payed: false}).find_each do |aSuscription|
        payments<<aSuscription.payment
      end

      payments
    end

    public
    def has_any_debt
      return debt_payments.size > 0
    end
end

app/models/menu_entry.rb
class MenuEntry < ActiveRecord::Base
  belongs_to :sucursal
  validates_presence_of :sucursal
end

app/models/payment.rb
class Payment < ActiveRecord::Base
	belongs_to :payable, polymorphic: true
	belongs_to :payment_type
	after_update :verify_payed

	private
	def type
		self.payment_type
	end

	private
	def verify_payed
		print "here!!\n\n\n---\n\n\n"
		if self.payed_changed? && self.payed == true
			self.update_column(:payment_date, Date.today)
		end
	end
end

app/models/payment_type.rb
class PaymentType < ActiveRecord::Base
	has_many :payments

end

app/models/publicity.rb
class Publicity < ActiveRecord::Base
  belongs_to :empresa
  has_one :payment, as: :payable
end

app/models/sub_category.rb
class SubCategory < ActiveRecord::Base
  belongs_to :category
  has_many :categorizations;
  has_many :sucursals, :through => :categorizations
end

app/models/sucursal.rb
class Sucursal < ActiveRecord::Base
	belongs_to :empresa
	has_many :menu_entries
	has_many :telefonos
	has_many :turnos
	has_many :categorizations
	has_many :sub_categories, :through => :categorizations
end

app/models/telefono.rb
class Telefono < ActiveRecord::Base
	belongs_to :sucursal
end

app/models/trovu_suscription.rb
class TrovuSuscription < ActiveRecord::Base
  belongs_to :empresa
  has_one :payment, as: :payable
  after_create :add_pendent_pay

  private 
  def add_pendent_pay
  	Payment.create(payable: self)
  end
end

app/models/turno.rb
class Turno < ActiveRecord::Base
	belongs_to :sucursal
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
 # http_basic_authenticate_with name: "trovuAdmin", password: "trovu"
  def index
  	@empresas = Empresa.all
  end

end

app/controllers/trovu_controller.rb
class TrovuController < ApplicationController
  respond_to :html, :js
  def index
  end

  def alCen
    #IMPLEMENTAR EL QUERY! PINGU! :(
  	#@empresas = SubCategory.find_by(nombre: 'Almuerzo-Cena').category.empresas
    @empresas = Empresa.all
  end

  def desMer
  	@empresas = Empresa.all
  end

  def masCercanos
  	@empresas = Empresa.all
  end

  def top10
  	@empresas = Empresa.all
  end

  def destacados
  	@empresas = Empresa.all
  end

  def nuevos
  	@empresas = Empresa.all
  end

  def search
  	word = params[:word]
    word = word.downcase
    @empresas = Empresa.find(:all, :conditions => ["nombre LIKE ?", prepare(word)])
  	@lat = -17.38533
  	@lng = -66.15442
  end

  def conocenos
  end

  def legal
  end
  def contactanos
  end
  def faq
  end
  def locales
  end

  private 
  def prepare(word)

    res = "%"

    word.each_char do |k|
      res = res + k + '%'
    end

    return res
  end


end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/empresas_helper.rb
module EmpresasHelper
end

app/helpers/menu_entries_helper.rb
module MenuEntriesHelper
end

app/helpers/payment_types_helper.rb
module PaymentTypesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/sucursals_helper.rb
module SucursalsHelper
end

app/helpers/trovu_helper.rb
module TrovuHelper
end

app/views/trovu/_fb_like.html.erb
<iframe src="//www.facebook.com/plugins/like.php?href=http%3A%2F%2Fwww.9gag.com&amp;width&amp;layout=standard&amp;action=like&amp;show_faces=true&amp;share=true&amp;height=80" scrolling="no" frameborder="0" style="border:none; overflow:hidden; height:80px;" allowTransparency="true" class = "fb-like"></iframe>

app/views/trovu/_footer.html.erb
<div id = "footer" class = "gradient">

	<div id = "footerCont">

		<div class = "fColumn">
			<p><%=link_to "Locales de Comida", controller: "trovu", action: "locales"%></p>
			<ul>
				<li>Almuerzo / Cena</li>
				<li>Desayuno / Merienda</li>
			</ul>
		</div>

		<div class = "fColumn">
			<p><%=link_to "Conocenos", controller: "trovu", action: "conocenos"%></p>
			<ul>
				<li>Quienes somos</li>
				<li><a href = "./conocenos#mision">Mision</a></li>
				<li><a href = "./conocenos#vision">Vision</a></li>
			</ul>
		</div>

		<div class = "fColumn">
			<p><%=link_to "Legal", controller: "trovu", action: "legal"%></p>
			<ul>
				<li><%=link_to "Condiciones de uso", controller: "trovu", action: "legal", id: "condiciones-uso"%></li>
				<li><%=link_to "Politica de privacidad - Usuarios", controller: "trovu", action: "legal", anchor: "privacidad-usuario"%></li>
				<li><%=link_to "Politica de privacidad - Empresas", controller: "trovu", action: "legal", anchor: "privacidad-empresas"%></li>
			</ul>
		</div>

		<div class = "fColumn">
			<p><%=link_to "Contactanos", controller: "trovu", action: "contactanos"%></p>
			<ul>
				<li>Empresas</li>
				<li>Usuarios</li>
				<li>Ayudanos a Mejorar</li>
			</ul>
		</div>

		<div class = "fColumn">
			<p><%=link_to "FAQ", controller: "trovu", action: "faq"%></p>
			<ul>
				<li>Trovu?</li>
				<li>faq</li>
				<li>Como usar trovu?</li>
				<li>Necesitas ayuda?</li>
			</ul>
		</div>

	</div>
</div> 

app/views/trovu/_initMapResults.html.erb
<script type="text/javascript"
      src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDLE-I4mF-_-5om09EbV5NvcZwDozeAJIg&sensor=false">
</script>

<script type="text/javascript">
	function initialize() {

		var latProm, lngProm, sucCount;
		latProm = lngProm = sucCount = 0;

		<% @empresas.each do |e|%>
			<% e.sucursals.each do |s|%>

				latProm += <%= s.latitud %>;
				lngProm += <%= s.longitud %>;
				sucCount++;
			<% end %>
		<% end %>

		latProm /= sucCount;
		lngProm /= sucCount;

		var mapOptions = {
			center: new google.maps.LatLng(latProm, lngProm),
			zoom: 16,
			mapTypeControl: false,
			streetViewControl: false
		};

		var map = new google.maps.Map(document.getElementById("map-canvas"),
		    mapOptions);
		
		var marker = new Array();
		var i = 0;
		<% @empresas.each do |e|%>
			
			<% e.sucursals.each do |s|%>

				marker[i] = new google.maps.Marker({
					position: new google.maps.LatLng(<%= s.latitud %>, <%= s.longitud %>),
					map: map,
					title: "<%=e.nombre%>",
					icon: "/assets/favicon.png"
				});

				i++;
			<% end %>
		<% end %>

	}
	google.maps.event.addDomListener(window, 'load', initialize);

</script>

app/views/trovu/_searchResult.html.erb
<%eCounter = 0%>
<% @empresas.each do |e| %>
	
	<%= form_tag empresa_count_a_view_path(e), remote: true, class: "e-counter", counter: eCounter do%>
		<% eCounter += 1 %>
		<h3 class = "empresa"> <%= e.nombre%> 
			<% if e.pays && e.on_date %>
			<%= image_tag "stars/"+e.estrellas.to_s+"stars.png", class: "star"%>
			<% end %>
		</h3>
	<% end %>



	<div class = "e-description" style = "background-image: url(<%=e.get_logo %> ); background-position: center center; background-repeat: no-repeat;"> 

	<% i = 1%>		
		<% e.sucursals.each do |s| %>	
			<div class = "s-description">
				<p>
					<strong> Sucursal nº <%= i %>: </strong> 
					<%= s.direccion %> 
				</p>
				<p><strong> Telefono(s): </strong> 
					<% s.telefonos.each do |t| %>
						<%= t.numero.to_s  + " / "%>
					<% end %>
				</p>
				<br>
			</div>
			<% i += 1%>
		<% end %> 

		<a class = "e-web" href="//<%=e.paginaWeb%>"><%=e.paginaWeb%></a>
	</div>
<% end %>

app/views/trovu/alCen.html.erb
<%=render "search"%>

app/views/trovu/conocenos.html.erb
<p><%=session[:user_id]%></p>
<h1 class = "title">Explora un mundo sin límites</h1>
<p>
	Tienes ganas de tomar un helado, comer una hamburguesa o un plato tradicional, pero no tienes el suficiente tiempo; tal vez conocer algo nuevo, que sea asequible para tu economía, pero no sabes donde encontrarlo.
</p>
<p>
	En TROVU tenemos la solución, explora en nuestra pagina web una infinidad de negocios que están cerca de tu fuente laboral, casa, colegio o universidad.
</p>
<p>
	El tiempo es algo valioso, por eso en TROVU lo valoramos y te ayudamos a manejarlo para que lo dediques en tu trabajo o en los que amas.
</p>

<h1 class = "title">Es para todos, simplemente comparte...</h1>
<p>
	Nuestra información es para todos, de libre y fácil acceso… Por que todos somos iguales y tenemos los mismos derechos.
</p>
<p>
	Usa TROVU y busca un buen restaurant para compartir con tus amigos un almuerzo, una cena, celebrar tu cumpleaños, tener esa cita especial o para salir un fin de semana con tu familia y convivir momentos inolvidables. En TROVU solo nos interesa tu bienestar y felicidad.
</p>
<p>
	Esa pregunta ¿Ahora donde comemos? o ¿Que comemos? Ya no será un problema, nuestra eficiencia se ve reflejada en la satisfacción de nuestros usuarios.
</p>

<h1 class = "title">Más fácil de usar... Imposible</h1>
<p>
	Muchas páginas tradicionales te obligan a marcar muchas opciones, de las cuales tendrás pocos o casi ningún resultado que satisfaga tus necesidades.
</p>
<p>
	En TROVU tenemos un revolucionario método de búsqueda, eficiente, real, práctico y fácil de usar; cualquier(a) persona puede usar TROVU sin ningún problema o sin tener algún conocimiento técnico.
</p>
<p>
	TROVU es una solución inteligente pensada para tus necesidades. Tu satisfacción y comodidad es el reflejo de la calidad de nuestro trabajo.
</p>

<h1 class = "title">Es libre y sin registros, úsalo donde sea</h1>
<p>
	Cansado de buscar en las páginas tradicionales un restaurant perfecto; pero antes, debes de llenar un tedioso formulario, dando tu información personal, solo para que te llegue correo basura o “spam” y al final no tengas un resultado deseado.
</p>
<p>
	Buscar en TROVU es TOTALMENTE GRATIS, y lo mejor LIBRE DE REGISTROS. Puedes acceder desde cualquier navegador (Google Chrome, Mozilla, Safari, Opera) de tu equipo (PC, Mac, Laptops, Notebook) o dispositivo móvil de cualquier plataforma (Symbian, iOS, Android, Windows Phone). Conéctate a la red y simplemente ENCUENTRA LO QUE QUIERAS .
</p>

<a name = "mision">
<h1 class = "title">Misión</h1>
<p>
	Trovu es una empresa que ofrece a la sociedad un servicio de información que le permite ser eficaz y eficiente al elegir lugares de su necesidad.
</p>

<a name = "vision">
<h1 class = "title">Visión</h1>
<p>
	Ser una empresa que ofrezca a la sociedad información completa y exacta de todos los lugares de la ciudad.
</p>

app/views/trovu/contactanos.html.erb
<!-- Check styles on: info.css-->
<h1 class = "title">Contáctanos</h1>

<p class = "blue-description justified">Trovu es una empresa pensada y dedicada tanto a los negocios jóvenes como a aquellos que poseen una larga trayectoria a: publicitarse, 

promocionarse y tener mayor clientela, de una manera productiva e innovadora; con el objetivo, de llegar a un mayor público de manera fácil, 

económica e interactiva. Los beneficios de pertenecer a Trovu son:</p>

<ul>
	<li>Publicidad gratuita por seis meses.</li>
	<li>Buena Publicidad por un buen precio.</li>
	<li>Visualización de su negocio a través de “Google Maps”.</li>
	<li>Excelente información y actualización constante de su(s) negocio(s).</li>
	<li>Consulta de estadísticas.</li>
	<li>Políticas de seguridad contra el fraude o publicidad engañosa.</li>

</ul>

app/views/trovu/desMer.html.erb
<%=render "search" %>

app/views/trovu/destacados.html.erb
<%=render "search"%>

app/views/trovu/legal.html.erb
<h1 class = "title" id = "condiciones-uso">Legal - Condiciones de uso</h1>
<p class = "blue-description centered">Por favor lea atentamente estas condiciones de uso antes de utilizar los servicios ofrecidos por TROVU. Estas condiciones de uso establecen términos y condiciones legales.</p>

<ol>
	<li>Una empresa o usuario al acceder o utilizar el servicio de TROVU, acepta todas las políticas y condiciones de nuestro manual. Estos pueden ser actualizados de manera constante.</li>
	<li>El acceso o visita a paginas son de uso público y no para el beneficio de otras empresas. Para aquellas que roben o hurten información producida por TROVU se aplicaran medidas legales referente a derechos de propiedad intelectual.</li>
	<li>Los usuarios pueden explorar el sitio y ver contenidos sin necesidad de registrarse. En cambio los negocios deben registrarse a TROVU y declarar, garantizar y comprometer a proporcionar a TROVU la información de registro correcta, veraz y completa. No hacerlo constituirá una violación de nuestras Políticas Legales.</li>
	<li>TROVU no reconocerá a: personas que crean cuentas para terceros, utilizar nombres de negocios que no sean reconocidos por los propietarios, negocios cuyos nombres ya estén asociados a TROVU o que estén sujetos a derechos de autor; y, negocios con nombres agresivos, vulgares, obscenos e ilegales.</li>	
	<li>El contenido publico o privado es responsabilidad exclusiva de la persona que origino dicho contenido, TROVU no puede garantizar la autenticidad de los contenidos que los negocios proponen al publico. Pero si podemos denunciar por ley, todo acto de desagravio en contra del público o ciudadanía que esta establecido en la Constitución Política del Estado Plurinacional de Bolivia.</li>
	<li>Los usuarios no podrán comentar o publicar en la información referente a los negocios afiliados, pero si pueden sugerir algunas mejoras en los links de sus paginas oficiales, los cuales están a disposición del publico en general.</li>
	<li>En la página se mantienen buenas normas de urbanidad, por lo tanto, todo comentario o comportamiento agresivo, amenaza o discriminatorio será denunciado por ley, contra aquel(los) o aquella(s) personas que emitan dichas publicaciones en contra del público o ciudadanía, siendo artículos establecidos en la Constitución Política del Estado Plurinacional de Bolivia.</li>
</ol>

<h1 class = "title" id = "privacidad-usuario">Legal – Política de Privacidad - Usuarios</h1>

<p class = "blue-description centered">Trovu es una empresa que se compromete a ofrecerte transparencia en nuestras prácticas de privacidad y control de los datos personales.</p>

<ol>
	<li>Trovu registra automáticamente en nuestro servidor la información de tu navegador o dispositivo, ubicación, dirección IP, información de cookies y los negocios a los cuales tu has visitado. Estos datos son tratados como información NO PERSONAL.</li>
	<li>Trovu NO PUBLICA O COMPARTE tu ubicación a terceros. Solamente utilizamos tu ubicación para darte información de aquellos negocios que estén mas cercanos.</li>
	<li>Todas las consultas a cualquier negocio(s) se realiza(n) de manera virtual, los cuales serán tomados en cuenta para brindarles datos estadísticos de visita a los negocios afiliados.</li>
	<li>Trovu no vende la información proporcionada de los negocios o usuarios, solamente publicitamos la información denuestros afiliados de manera VOLUNTARIA a terceros, bajo FIRMA y AUTORIZACION de los dueños.</li>
	<li>Uno de los propósitos es ayudar a los usuarios a conocer nuevos NEGOCIOS, también brindar la información de promociones o beneficios que brindan los locales, sin embargo TROVU no se hace responsable por fraudes emitidos por los negocios.</li>
	<li>Solamente se podrá divulgar información cuando creamos de buena fe sea necesaria, para cumplir con la ley, hacer cumplir o aplicar nuestras condiciones de uso y otros acuerdos, proteger derechos de nuestros empleados o usuarios; para la protección contra el fraude y reducción de riesgo económico.</li>
</ol>

<h1 class = "title" id = "privacidad-empresas">Legal – Política de Privacidad - Empresas</h1>

<p class = "blue-description centered">Legal – Política de Privacidad - Empresas</p>

<ol>
	<li>Para registrarse a TROVU una empresa deberá llenar un “formulario básico”, cuyas preguntas son: nombre del negocio, dirección, teléfonos de referencia, días, horarios de atención y dirección web o pagina de Facebook o Twitter. La ubicación a través de los mapas de Google corre por cuenta de los responsables de TROVU. Estos datos son tratados como Información pública y serán publicados en la pagina de TROVU para la apreciación de los usuarios.</li>
	<li>En el formulario básico, se solicitarán el nombre del propietario del negocio, carnet de identidad, número de celular y/o correos electrónicos de referencia, con el fin de informar a nuestros afiliados acerca de promociones, ofertas o comunicados que realice TROVU. Estos datos son tratados como información personal y no serán publicados en la pagina de TROVU.</li>
	<li>Trovu no vende la información personal o publica proporcionada de los negocios o usuarios, solamente publicitamos la información de nuestros afiliados, de manera VOLUNTARIA al público, bajo FIRMA y AUTORIZACIÓN de los dueños.
	</li>
	<li>Una vez terminado el registro, una empresa nueva goza de 6 meses de prueba GRATUITOS, esto permite al negocio publicitarse de manera efectiva y a la vez. Por esta razón el registro es totalmente libre, voluntario y sin compromisos.</li>
	<li>Si luego de los 6 meses, una empresa desea continuar en la página de TROVU, está pagará un costo de renovación de Bs. 10 (diez bolivianos) por local y seis meses de registro para negocios pequeños, Bs 20 para negocios medianos; y, Bs 30 para negocios grandes o cadenas de comida. Los afiliados serán notificados por mail acerca de su renovación.</li>
	<li>En caso de ya no continuar con nuestros servicios, los suscritos deberán informar por un correo electrónico y llenar una encuesta de eficiencia. En un periodo de 24 horas toda su información será eliminada de la pagina.</li>
	<li>En TROVU los afiliados podrán añadir información extra como: el contenido de su menú, actividades que haga el negocio (promociones, rebajas, conciertos de grupos en vivo y/u ofertas que hagan al publico). Esto supone un costo adicional, los cuales serán proporcionados por los agentes de TROVU.</li>
	<li>Uno de los propósitos es ayudar a los usuarios a conocer nuevos NEGOCIOS, pero también proporcionar información referente a promociones o beneficios que brindan los locales, sin embargo TROVU no se hace responsable por fraudes emitidos por sus afiliados. Pero si podemos denunciar por ley, todo acto de desagravio en contra del público o ciudadanía que esta establecido en la Constitución Política del Estado Plurinacional de Bolivia.</li>
	<li>Todas las consultas a cualquier negocio(s) se realiza de manera virtual, los cuales serán tomados en cuenta para brindarles datos estadísticos de VISITA A LOS NEGOCIOS DE MANERA MENSUAL. De esta manera, nuestros afiliados podrán observar el interés del público a su(s) negocio(s) y aplicar nuevas estrategias de publicidad, marketing o promociones</li>
	<li>Si una empresa decide terminar su contrato con TROVU, todos los beneficios e historial serán eliminados de nuestra base de datos. </li>
	<li>Solamente TROVU divulgará INFORMACIÓN PERSONAL cuando creamos de buena fe sea necesaria, para cumplir con la ley, hacer cumplir o aplicar nuestras condiciones de uso y otros acuerdos, proteger derechos de nuestros empleados o usuarios; para la protección contra el fraude y reducción de riesgo económico.</li>
</ol>

app/views/trovu/masCercanos.html.erb
<%=render "search"%>

app/views/trovu/nuevos.html.erb
<%=render "search"%>

app/views/trovu/search.html.erb
<div id = "accordion">


	<%=render "searchResult"%>

</div>

<%= render "initMapResults"%>


<div id = "map-canvas"></div>
<div class = "clear"></div>

app/views/trovu/top10.html.erb
<%=render "search"%>