config/routes.rb
Trovu::Application.routes.draw do

  get '/admin', to: 'admin#index', as: '/' 
  resources :empresas do 
    resources :sucursals do
      resources :menu_entries
    end
    resources :trovu_suscriptions 
    resources :payments
    post "/count_a_view" => 'empresas#count_a_view'
    get "/debts" => 'empresas#debts'
  end

  resources :payment_types

  get "admin/index"
  get "/" => "trovu#index"
  get "/almuerzo_cena" => "trovu#alCen" 
  get "/desayuno_merienda" => "trovu#desMer"
  get "/mas_cercanos" => "trovu#masCercanos"
  get "/top10" => "trovu#top10"
  get "/destacados" => "trovu#destacados"
  get "/nuevos" => "trovu#nuevos"
  get "/conocenos" => "trovu#conocenos"
  get "/legal" => "trovu#legal"
  get "/contactanos" => "trovu#contactanos"
  get "/faq" => "trovu#faq"
  get "/locales" => "trovu#locales"
  match '/search', to: 'trovu#search', via: "get"
  root "trovu#index"
end

app/models/categorization.rb
class Categorization < ActiveRecord::Base
  belongs_to :sucursal
  belongs_to :sub_category
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :sub_categories
end

app/models/empresa.rb
class Empresa < ActiveRecord::Base
	has_many :sucursals
	has_many :publicidads
	has_many :trovu_suscriptions
	validates_uniqueness_of :nombre 
  	has_attached_file :logotipo, :styles => { :medium => "300x300>", :mini => "30x30>" },
	:url  => "/assets/pictures/:id/:style/:basename.:extension",
    :path => ":rails_root/public/assets/pictures/:id/:style/:basename.:extension",
    :default_url => '/assets/defaults/rest/restaurant-default_:style.png'
    validates_attachment_size :logotipo, :less_than => 1.megabytes
  	validates_attachment_content_type :logotipo, :content_type => /\Aimage\/.*\Z/

    after_create :check_suscribed
    after_update :check_pays

    private
    def check_pays
      if (self.pays_changed? && self.pays == true)
        add_suscription
      end
    end

    private
    def check_suscribed
      if (self.pays)
        add_suscription
      end
    end

    private
    def add_suscription
        
        expireDate = Date.today + 1.year
        suscription = TrovuSuscription.create(empresa: self, expires_on: expireDate);
    end

  	public
  	def expiration_date
  		expDate = nil

  		if self.pays
  			expDate = trovu_suscriptions.last.expires_on
  		else
  			expDate = Date.today - 1.day
  		end
  		return expDate
  	end

  	public 
  	def on_date
  		return self.expiration_date >= Date.today
  	end

    public
    def count_a_view
      lastCount = self.visit_count
      if (lastCount == nil)
        lastCount = 0
      end
      self.visit_count = lastCount + 1
      self.save
    end
    public
    def get_logo
      logo = nil
      if self.pays
        logo = self.logotipo
      end
      return logo
    end

    public
    def debt_payments

      payments = []
      TrovuSuscription.includes(:payment).joins(:payment).where(empresa: self, payments: {payed: false}).find_each do |aSuscription|
        payments<<aSuscription.payment
      end

      payments
    end

    public
    def has_any_debt
      return debt_payments.size > 0
    end
end

app/models/menu_entry.rb
class MenuEntry < ActiveRecord::Base
  belongs_to :sucursal
  validates_presence_of :sucursal
end

app/models/payment.rb
class Payment < ActiveRecord::Base
	belongs_to :payable, polymorphic: true
	belongs_to :payment_type
	after_update :verify_payed

	private
	def type
		self.payment_type
	end

	private
	def verify_payed
		print "here!!\n\n\n---\n\n\n"
		if self.payed_changed? && self.payed == true
			self.update_column(:payment_date, Date.today)
		end
	end
end

app/models/payment_type.rb
class PaymentType < ActiveRecord::Base
	has_many :payments

end

app/models/publicity.rb
class Publicity < ActiveRecord::Base
  belongs_to :empresa
  has_one :payment, as: :payable
end

app/models/sub_category.rb
class SubCategory < ActiveRecord::Base
  belongs_to :category
  has_many :categorizations;
  has_many :sucursals, :through => :categorizations
end

app/models/sucursal.rb
class Sucursal < ActiveRecord::Base
	belongs_to :empresa
	has_many :menu_entries
	has_many :telefonos
	has_many :turnos
	has_many :categorizations
	has_many :sub_categories, :through => :categorizations
end

app/models/telefono.rb
class Telefono < ActiveRecord::Base
	belongs_to :sucursal
end

app/models/trovu_suscription.rb
class TrovuSuscription < ActiveRecord::Base
  belongs_to :empresa
  has_one :payment, as: :payable
  after_create :add_pendent_pay

  private 
  def add_pendent_pay
  	Payment.create(payable: self)
  end
end

app/models/turno.rb
class Turno < ActiveRecord::Base
	belongs_to :sucursal
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
 # http_basic_authenticate_with name: "trovuAdmin", password: "trovu"
  def index
  	@empresas = Empresa.all
  end

end

app/controllers/menu_entries_controller.rb
class MenuEntriesController < ApplicationController
	respond_to :html, :js
	layout "admin"

	def index
		@empresa = Empresa.find(params[:empresa_id])
		@sucursal = Sucursal.find(params[:sucursal_id])		
	end

	def new
		@empresa = Empresa.find(params[:empresa_id])
		@sucursal = Sucursal.find(params[:sucursal_id])
	end

	def create
		sucursal = Sucursal.find(params[:sucursal_id])
		@entry = MenuEntry.new(menu_entry_params)
		@entry.sucursal = sucursal
		@entry.save

		redirect_to 
	end

	def edit
		@entry = MenuEntry.find(params[:id])
	end

	def update
		entry = MenuEntry.find(params[:id])
		entry.update(menu_entry_params)
		respond_to do |format|
			format.html {redirect_to empresa_sucursal_menu_entries_path(entry.sucursal.empresa, entry.sucursal)}
		end	
	end

	def destroy
		@entry = MenuEntry.find(params[:id])
		@entry.destroy

		redirect_to edit_empresa_sucursal_path(params[:empresa_id], params[:sucursal_id])
	end

	private 
	def menu_entry_params
		params.require(:menu_entry).permit(:plato, :descripcion, :precio, :sucursal_id)
		
	end
end

app/controllers/trovu_controller.rb
class TrovuController < ApplicationController
  respond_to :html, :js
  def index
  end

  def alCen
    #IMPLEMENTAR EL QUERY! PINGU! :(
  	#@empresas = SubCategory.find_by(nombre: 'Almuerzo-Cena').category.empresas
    @empresas = Empresa.all
  end

  def desMer
  	@empresas = Empresa.all
  end

  def masCercanos
  	@empresas = Empresa.all
  end

  def top10
  	@empresas = Empresa.all
  end

  def destacados
  	@empresas = Empresa.all
  end

  def nuevos
  	@empresas = Empresa.all
  end

  def search
  	word = params[:word]
    word = word.downcase
    @empresas = Empresa.find(:all, :conditions => ["nombre LIKE ?", prepare(word)])
  	@lat = -17.38533
  	@lng = -66.15442
  end

  def conocenos
  end

  def legal
  end
  def contactanos
  end
  def faq
  end
  def locales
  end

  private 
  def prepare(word)

    res = "%"

    word.each_char do |k|
      res = res + k + '%'
    end

    return res
  end


end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/empresas_helper.rb
module EmpresasHelper
end

app/helpers/menu_entries_helper.rb
module MenuEntriesHelper
end

app/helpers/payment_types_helper.rb
module PaymentTypesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/sucursals_helper.rb
module SucursalsHelper
end

app/helpers/trovu_helper.rb
module TrovuHelper
end

app/views/menu_entries/_edit.html.erb
<h3>Editar <%=@entry.plato%></h3>

<%= form_for @entry, url: empresa_sucursal_menu_entry_path(@entry.sucursal.empresa, @entry.sucursal, @entry), method: :patch do |f|%>


	<%=render 'entry_form', f: f%>

<%=f.submit "Guardar Cambios"%>
	
<% end %>

app/views/menu_entries/_entry_form.html.erb
<table>
	<tr>
		<td><%=f.label :plato, "Nombre item:"%></td>
		<td><%=f.text_field :plato, required: :true%></td>
	</tr>
	<tr>
		<td><%=f.label :precio, "Precio:"%></td>
		<td><%=f.number_field :precio, required: :true%></td>
	</tr>
	<tr>
		<td><%=f.label :descripcion, "Descripción:"%></td>
		<td><%=f.text_field :descripcion%></td>
	</tr>
</table>

app/views/menu_entries/_new.html.erb
<h4>Nuevo Menu Item</h4>
<div class = "bot-left-border">
<%= form_for :menu_entry, url: empresa_sucursal_menu_entries_path(@empresa, @sucursal) do |f|%>
	
	<%=render 'entry_form', f: f%>
	<%= f.submit %>
<% end %>
</div>
<br><br>

app/views/menu_entries/_show.html.erb
<h4>Menu:</h4>
<table>
<tr>
	<th>Item</th>
	<th>Precio (Bs.)</th>
</tr>
<%@sucursal.menu_entries.each do |m|%>
	<tr class = "menu-entry">
		<td><%=m.plato%></td>
		<td><%=m.precio%></td>

	</tr>
	<tr class = "menu-entry"> 
		<td><i class = "small-font"><%=m.descripcion%></i></td>
		<td><%=button_to "Eliminar", empresa_sucursal_menu_entry_path(@sucursal.empresa, @sucursal, m), 
		method: :delete, data: {confirm: "¿Estas seguro?"}%></td>
		<%if show_edit%>
		<td> <%=link_to "Editar", edit_empresa_sucursal_menu_entry_path(@sucursal.empresa, @sucursal, m), remote: :true%></td>
		<%end%>
	</tr>
<% end %>
</table>

app/views/menu_entries/edit.js.erb
$(".entry-form").show();
$('#edit-entry').hide().html("<%= escape_javascript(render 'edit') %>").slideDown();

app/views/menu_entries/index.html.erb
<div class = "left-column">
	<%=render 'show', show_edit: :true%>
	<div id = "new-menu-entry"></div>
	<%=link_to "Añadir menu item", new_empresa_sucursal_menu_entry_path(@sucursal.empresa, @sucursal), remote: :true%>
</div>
<div class = "right-column entry-form">
	<div id = "edit-entry"></div>
</div>

app/views/menu_entries/new.html.erb
<%=render 'show', show_edit: :true%>
<div id = "new-menu-entry"></div>
<%=link_to "Añadir menu item", new_empresa_sucursal_menu_entry_path(@sucursal.empresa, @sucursal), remote: :true%>

app/views/menu_entries/new.js.erb
$('#new-menu-entry').hide().html("<%=escape_javascript(render 'new')%>").slideDown();