config/routes.rb
Trovu::Application.routes.draw do

  get '/admin', to: 'admin#index', as: '/' 
  resources :empresas do 
    resources :sucursals do
      resources :menu_entries
    end
    resources :trovu_suscriptions 
    resources :payments
    post "/count_a_view" => 'empresas#count_a_view'
    get "/debts" => 'empresas#debts'
  end

  resources :payment_types

  get "admin/index"
  get "/" => "trovu#index"
  get "/almuerzo_cena" => "trovu#alCen" 
  get "/desayuno_merienda" => "trovu#desMer"
  get "/mas_cercanos" => "trovu#masCercanos"
  get "/top10" => "trovu#top10"
  get "/destacados" => "trovu#destacados"
  get "/nuevos" => "trovu#nuevos"
  get "/conocenos" => "trovu#conocenos"
  get "/legal" => "trovu#legal"
  get "/contactanos" => "trovu#contactanos"
  get "/faq" => "trovu#faq"
  get "/locales" => "trovu#locales"
  match '/search', to: 'trovu#search', via: "get"
  root "trovu#index"
end

app/models/categorization.rb
class Categorization < ActiveRecord::Base
  belongs_to :sucursal
  belongs_to :sub_category
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :sub_categories
end

app/models/empresa.rb
class Empresa < ActiveRecord::Base
	has_many :sucursals
	has_many :publicidads
	has_many :trovu_suscriptions
	validates_uniqueness_of :nombre 
  	has_attached_file :logotipo, :styles => { :medium => "300x300>", :mini => "30x30>" },
	:url  => "/assets/pictures/:id/:style/:basename.:extension",
    :path => ":rails_root/public/assets/pictures/:id/:style/:basename.:extension",
    :default_url => '/assets/defaults/rest/restaurant-default_:style.png'
    validates_attachment_size :logotipo, :less_than => 1.megabytes
  	validates_attachment_content_type :logotipo, :content_type => /\Aimage\/.*\Z/

    after_create :check_suscribed
    after_update :check_pays

    private
    def check_pays
      if (self.pays_changed? && self.pays == true)
        add_suscription
      end
    end

    private
    def check_suscribed
      if (self.pays)
        add_suscription
      end
    end

    private
    def add_suscription
        
        expireDate = Date.today + 1.year
        suscription = TrovuSuscription.create(empresa: self, expires_on: expireDate);
    end

  	public
  	def expiration_date
  		expDate = nil

  		if self.pays
  			expDate = trovu_suscriptions.last.expires_on
  		else
  			expDate = Date.today - 1.day
  		end
  		return expDate
  	end

  	public 
  	def on_date
  		return self.expiration_date >= Date.today
  	end

    public
    def count_a_view
      lastCount = self.visit_count
      if (lastCount == nil)
        lastCount = 0
      end
      self.visit_count = lastCount + 1
      self.save
    end
    public
    def get_logo
      logo = nil
      if self.pays
        logo = self.logotipo
      end
      return logo
    end

    public
    def debt_payments

      payments = []
      TrovuSuscription.includes(:payment).joins(:payment).where(empresa: self, payments: {payed: false}).find_each do |aSuscription|
        payments<<aSuscription.payment
      end

      payments
    end

    public
    def has_any_debt
      return debt_payments.size > 0
    end
end

app/models/menu_entry.rb
class MenuEntry < ActiveRecord::Base
  belongs_to :sucursal
  validates_presence_of :sucursal
end

app/models/payment.rb
class Payment < ActiveRecord::Base
	belongs_to :payable, polymorphic: true
	belongs_to :payment_type
	after_update :verify_payed

	private
	def type
		self.payment_type
	end

	private
	def verify_payed
		print "here!!\n\n\n---\n\n\n"
		if self.payed_changed? && self.payed == true
			self.update_column(:payment_date, Date.today)
		end
	end
end

app/models/payment_type.rb
class PaymentType < ActiveRecord::Base
	has_many :payments

end

app/models/publicity.rb
class Publicity < ActiveRecord::Base
  belongs_to :empresa
  has_one :payment, as: :payable
end

app/models/sub_category.rb
class SubCategory < ActiveRecord::Base
  belongs_to :category
  has_many :categorizations;
  has_many :sucursals, :through => :categorizations
end

app/models/sucursal.rb
class Sucursal < ActiveRecord::Base
	belongs_to :empresa
	has_many :menu_entries
	has_many :telefonos
	has_many :turnos
	has_many :categorizations
	has_many :sub_categories, :through => :categorizations
end

app/models/telefono.rb
class Telefono < ActiveRecord::Base
	belongs_to :sucursal
end

app/models/trovu_suscription.rb
class TrovuSuscription < ActiveRecord::Base
  belongs_to :empresa
  has_one :payment, as: :payable
  after_create :add_pendent_pay

  private 
  def add_pendent_pay
  	Payment.create(payable: self)
  end
end

app/models/turno.rb
class Turno < ActiveRecord::Base
	belongs_to :sucursal
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
 # http_basic_authenticate_with name: "trovuAdmin", password: "trovu"
  def index
  	@empresas = Empresa.all
  end

end

app/controllers/empresas_controller.rb
class EmpresasController < ApplicationController
	layout "admin"
#	http_basic_authenticate_with name: "trovuAdmin", password: "trovu"
	def new
		@f
	end
	def create
		empresa = Empresa.create(empresa_params)
	
		sucursal = Sucursal.create(direccion: params[:empresa][:direccion], 
								latitud: params[:empresa][:latitud],
								longitud: params[:empresa][:longitud],
								empresa: empresa)

		if empresa.pays
			redirect_to edit_empresa_payment_path(empresa, empresa.trovu_suscriptions.last.payment)
		else
			redirect_to controller: "admin", action: "index"
		end
	end

	def show
		@empresa = Empresa.find(params[:id])
	end	

	def edit
		@empresa = Empresa.find(params[:id])	
		@f
	end	

	def update
		empresa = Empresa.find(params[:id])
		empresa.update(empresa_params)
		empresa.sucursals[0].update(direccion: params[:empresa][:direccion])
		redirect_to empresa
	end

	def destroy

		@empresa = Empresa.find(params[:id])
		@empresa.destroy
		redirect_to controller: "admin", action: "index"
	end

	def count_a_view	
		empresa = Empresa.find(params[:empresa_id])
		empresa.count_a_view
	end

	def debts
		@empresa = Empresa.select(:nombre, :id).find(params[:empresa_id])
		@payments = @empresa.debt_payments
	end

	private 
	def empresa_params
		params.require(:empresa).permit(:nombre, :direccion, :paginaWeb, :facebook, :twitter, :logotipo, :precioRelativo, :estrellas, :pays)
	end

end

app/controllers/trovu_controller.rb
class TrovuController < ApplicationController
  respond_to :html, :js
  def index
  end

  def alCen
    #IMPLEMENTAR EL QUERY! PINGU! :(
  	#@empresas = SubCategory.find_by(nombre: 'Almuerzo-Cena').category.empresas
    @empresas = Empresa.all
  end

  def desMer
  	@empresas = Empresa.all
  end

  def masCercanos
  	@empresas = Empresa.all
  end

  def top10
  	@empresas = Empresa.all
  end

  def destacados
  	@empresas = Empresa.all
  end

  def nuevos
  	@empresas = Empresa.all
  end

  def search
  	word = params[:word]
    word = word.downcase
    @empresas = Empresa.find(:all, :conditions => ["nombre LIKE ?", prepare(word)])
  	@lat = -17.38533
  	@lng = -66.15442
  end

  def conocenos
  end

  def legal
  end
  def contactanos
  end
  def faq
  end
  def locales
  end

  private 
  def prepare(word)

    res = "%"

    word.each_char do |k|
      res = res + k + '%'
    end

    return res
  end


end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/empresas_helper.rb
module EmpresasHelper
end

app/helpers/menu_entries_helper.rb
module MenuEntriesHelper
end

app/helpers/payment_types_helper.rb
module PaymentTypesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/sucursals_helper.rb
module SucursalsHelper
end

app/helpers/trovu_helper.rb
module TrovuHelper
end

app/views/empresas/_almuerzoCena.html.erb
<%= @f.label :restaurante%><%=check_box_tag :restaurante%><br><%= @f.label :pension%><%=check_box_tag :pension%><br><%= @f.label :snack%><%=check_box_tag :snack%><br><%= @f.label :heladeria%><%=check_box_tag :heladeria%><br><%= @f.label :confiteria%><%=check_box_tag :confiteria%><br><%= @f.label :cafe%><%=check_box_tag :cafe%><br><%= @f.label :pollo%><%=check_box_tag :pollo%><br><%= @f.label :fast_food%><%=check_box_tag :fast_food%><br><%= @f.label :plaza_de_comidas%><%=check_box_tag :plaza_de_comidas%><br><%= @f.label :tradicional%><%=check_box_tag :tradicional%>

app/views/empresas/_desayunoMerienda.html.erb
<%= @f.label :salteñeria%><%=check_box_tag :salteñeria%><br><%= @f.label :empanadas%><%=check_box_tag :empanadas%><br><%= @f.label :reposteria%><%=check_box_tag :reposteria%><br><%= @f.label :snack%><%=check_box_tag :snack%><br><%= @f.label :cafe%><%=check_box_tag :cafe%><br><%= @f.label :tucumanas%><%=check_box_tag :tucumanas%><br><%= @f.label :panaderia%><%=check_box_tag :panaderia%><br><%= @f.label :heladeria%><%=check_box_tag :heladeria%><br>

app/views/empresas/_edit_empresaForm.html.erb
<table>
	<tr>
		<td><%=form.label :direccion, "Direccion:" %></td>
		<td><%=form.text_field :direccion, :required => true%></td>
	</tr>
	<tr>
		<td><%=form.label :precioRelativo, "Precio relativo:"%></td>
		<td><%=form.number_field :precioRelativo, :required => true%></td>
	</tr>
	<tr>
		<td><%=form.label :paginaWeb, "paginaWeb"%></td>
		<td><%=form.text_field :paginaWeb, :required => true%></td>
	</tr>
	<tr>
		<td><%=form.label :facebook, "Facebook:"%></td>
		<td><%=form.text_field :facebook, :required => true%></td>
	</tr>
	<tr>	
		<td><%=form.label :twitter, "Twitter:"%></td>
		<td><%=form.text_field :twitter, :required => true%></td>
	</tr>

</table>

<%=render 'payedForm', form: form%>

app/views/empresas/_empresaForm.html.erb
<% @f = form %>
  <%=render "newScript"%>
  <div class = "left-column">
  <h3>Datos de la Empresa</h3>
  <table>
  	<tr>
      <td><%=form.label :nombre, "Nombre:" %></td>
  	  <td><%=form.text_field :nombre, :required => true%></td>
  	</tr>
  	<tr>
  	  <td><%=form.label :direccion, "Direccion:"%></td>
  	  <td><%=form.text_field :direccion, :required => true, id: "locNameInput"%></td>
  	</tr>
    <tr>
      <td><%=form.label :latitud%></td>
      <td><%=form.number_field :latitud, :required => true, id: "latInput", step: :any%></td>
    </tr>
    <tr>
      <td><%=form.label :longitud%></td>
      <td><%=form.number_field :longitud, :required => true, id: "lngInput", step: :any%></td>
    </tr>
  	<tr>
  		<td><%=form.label :precioRelativo, "Precio Promedio:"%></td>
  		<td><%=form.number_field :precioRelativo, :required => true%></td>
  	</tr>
  	<tr>
  		<td><%=form.label :categoria, "Categoria"%></td>
  		<td><%=select_tag :categoria, options_for_select([["-- Selecciona Categoria --", "..."],["Almuerzo/Cena", "Almuerzo/Cena"],["Desayuno/Merienda", "Desayuno/Merienda"]]), :onchange => "subCategoryChange()"%></td>
  	</tr>
  	<tr>
  		<td><%=form.label :subCategoria, "SubCategoria:"%></td>
  		<td><div id = "subCategoria"></div></td>
  	</tr>
  	<tr>
  		<td><%=form.label :telefono, "Telefono:"%></td>
  		<td><%=form.text_field :telefono, :required => true%></td>
  	</tr>
  	<tr>
  		<td><%=form.label :celular, "Celular:"%></td>
  		<td><%=form.text_field :celular%></td>
  	</tr>
  	<tr>
  		<td><%=form.label :paginaWeb, "Pagina Web:"%></td>
  		<td><%=form.text_field :paginaWeb%></td>
  	</tr>
  	<tr>
  		<td><%=form.label :facebook, "Facebook:"%></td>
  		<td><%=form.text_field :facebook%></td>
  	</tr>
  	<tr>
  		<td><%=form.label :twitter, "Twitter:"%></td>
  		<td><%=form.text_field :twitter%></td>
  	</tr>
  	<tr></tr>
  </table>

  <h3><%=form.label :pays, "Informacion $Trovu"%> <%=form.check_box :pays, :onchange => "enableInput()"%></h3>

  <table class = "pays">
    <tr>
      <td><%=form.label :logotipo, "Logo:"%></td>
      <td><%=form.file_field :logotipo%></td>
    </tr>
    <tr>
      <td>Estrellas: </td>
      <td><%=form.select :estrellas, options_for_select(["0", "1", "2", "3", "4", "5"], "0")%></td>
    </tr>
  </table>



  </div>

  <div class = "right-column">
  <%=render 'locationPicker'%>
  <%=render 'payedScript'%>
  <h3>Datos del Responsable</h3>
  <table>
  	<tr>
  		<td><%=form.label :responsable, "Responsable a cargo:"%></td>
  		<td><%=form.text_field :responsable, :required => true%></td>
  	</tr>
  	<tr>
  		<td><%=form.label :telefonoResp, "Telefono:"%></td>
  		<td><%=form.text_field :telefonoResp%></td>
  	</tr>
  	<tr>
  		<td><%=form.label :celularResp, "Celular:"%></td>
  		<td><%=form.text_field :celularResp%></td>
  	</tr>
  	<tr>
  		<td><%=form.label :emailResp, "E-mail:"%></td>
  		<td><%=form.text_field :emailResp%></td>
  	</tr>
  </table>
  </div>
  <div class = "clear"></div>

app/views/empresas/_locationPicker.html.erb
<script type="text/javascript" src='http://maps.google.com/maps/api/js?sensor=false&libraries=places'></script>
<%=javascript_include_tag "locationPicker"%>

<div id = 'locationPicker'></div>
<script type="text/javascript">
	
	var latInput = $('#latInput');
	var lngInput = $('#lngInput');

	var lat = latInput.val() != "" ? latInput.val() : -17.38533;

	var lng = lngInput.val() != "" ? lngInput.val() : -66.15442;

	$('#locationPicker').locationpicker({
		location: {latitude: lat, longitude: lng},
		radius: 30,
		inputBinding: {
			latitudeInput: latInput,
			longitudeInput: lngInput,
			locationNameInput: $('#locNameInput')
		}
	});	
</script>

app/views/empresas/_newScript.html.erb
<script type="text/javascript">
function subCategoryChange(){
	var subCategoria = document.getElementById("subCategoria");
	var categoria = document.getElementById("categoria").value;
	subCategoria.innerHTML = "";
	if (categoria === "Almuerzo/Cena")
		subCategoria.innerHTML = '<%=render "almuerzoCena"%>';
	if (categoria === "Desayuno/Merienda")
		subCategoria.innerHTML = '<%=render "desayunoMerienda"%>';
}

</script>

app/views/empresas/_payedForm.html.erb
<h3><%=form.label :pays, "Informacion $Trovu"%> <%=form.check_box :pays, :onchange => "enableInput()"%></h3>

<table class = "pays">
    <tr>
      <td><%=form.label :logotipo, "Logo:"%></td>
      <td><%=form.file_field :logotipo%></td>
    </tr>
    <tr>
      <td>Estrellas: </td>
      <td><%=form.select :estrellas, options_for_select(["0", "1", "2", "3", "4", "5"], "0")%></td>
    </tr>
  </table>

<%=render 'payedScript'%>

app/views/empresas/_payedScript.html.erb
<script type="text/javascript">
	var isDisabled = false;

	function enableInput(){
		console.log("ok");
		isDisabled = !isDisabled;
		$('.pays input, .pays select').prop("disabled", isDisabled);
	};

	$('.payed').ready(function(){
		enableInput();
	});
	
</script>

app/views/empresas/debts.html.erb
<h2>Deudas de <%=link_to @empresa.nombre, empresa_path(@empresa)%></h2>
<h4>Total: <%= @payments.size%></h4>



<p>CONTINUAR ACA</p>

app/views/empresas/edit.html.erb
<h2>Editar empresa</h2>

<div id = "edit-form">
<%= form_for @empresa, url: empresa_path(@empresa), method: :patch do |f|%>

	<%=render 'edit_empresaForm', form: f%>
	<%=f.submit "Guardar"%>
<% end %>


<%i = 0%>
<%lat = 0%>
<%lon = 0%>
<% @empresa.sucursals.each do |s| %>
	<% i = i+1%>
	<% lat += s.latitud %>
	<% lon += s.longitud %>
	<%= link_to "Sucursal "+i.to_s, edit_empresa_sucursal_path(@empresa, s) %>
<% end %>
</div>
<% lat = lat / i%>
<% lon = lon / i%>

<div id = "map-canvas" >

</div>


<%= render "admin/show_empresa_sucursals", empresa: @empresa, lat: lat, lng: lon%>

<div class = "clear"></div>

app/views/empresas/new.html.erb
<h2>Afiliar nueva empresa</h2>

<%=form_for :empresa, url: empresas_path do |f|%>
  <%=render 'empresaForm', form: f %>
<%=f.submit%>
<% end %>

app/views/empresas/show.html.erb
<div class = "left-column">
	<h3><%= @empresa.nombre %></h3>
	<%= image_tag @empresa.logotipo.url(:medium)%><br>

	<%i = 0%>
	<%lat = 0%>
	<%lng = 0%>
	<% @empresa.sucursals.each do |s|%>
		<%=s.direccion%><br>
		<%i = i+1%>
		<%lat += s.latitud%>
		<%lng += s.longitud%>
	<%end%>

	<% if @empresa.pays%>
		<div class = "border">

			<p >Empresa <b>Trovu</b></p><br>
			<div class = "small-font">
			<i>Suscripcion termina en: <%=@empresa.expiration_date.to_s%></i><br>
			<%=link_to "Ver suscripciones", empresa_trovu_suscriptions_path(@empresa), class: 'small-font'%>
			<p><b>Cuenta de visitas:</b> <%= @empresa.visit_count == nil ? 0 :  @empresa.visit_count %></p>
			<%if @empresa.has_any_debt%>
				<p>Esta empresa tiene deudas. <%=link_to "Ver deudas", empresa_debts_path(@empresa)%></p>
				
			<%end%>
			</div>
		</div>

	<%else%>
		<p><i>Empresa normal</i></p>
	<% end %>

	<p>
		<i>Afiliada en: <%= @empresa.created_at%></i>
	</p>


	<%=link_to "Editar", edit_empresa_path(@empresa)%> <br>
	<%=link_to "Volver", controller: "admin", action: "index"%>

</div>

<div class = "rigth-column">
	<div id = "map-canvas"></div>
</div>

<div class = "clear"></div>

<%=render "admin/show_empresa_sucursals", empresa: @empresa, lat: lat/i, lng: lng/i%>